version: '3.8'

services:
  flask-app:
    build:
      context: ./app
    container_name: flask-app-container
    ports:
      - "5000:5000"
    networks:
      - flask-network
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: "redis:latest"
    container_name: redis-container
    networks:
      - flask-network
    ports:
      - "6379:6379"

networks:
  flask-network:
    driver: bridge
