name: App Build Validation

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  app-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt
